"""
Midnight ZK AI Inference — Demo
AI Track · INTO THE MIDNIGHT Hackathon

Demonstrates privacy-preserving machine learning with zero-knowledge proofs.
Private inputs never leave this machine - only proofs are generated.

Run: python examples/ai_inference.py
"""

from midnight_py import MidnightClient
from midnight_py.exceptions import ModelNotTrainedError, ProofServerConnectionError
from pathlib import Path
import sys


def main():
    # Demo features (Iris setosa sample)
    features = [5.1, 3.5, 1.4, 0.2]
    
    # Print header
    print("=" * 54)
    print("     Midnight ZK AI Inference - Demo")
    print("     AI Track - INTO THE MIDNIGHT Hackathon")
    print("=" * 54)
    print()
    
    # a) Create MidnightClient
    try:
        client = MidnightClient(
            network="undeployed",
            wallet_address="mn_addr_undeployed1zaa268rc7sjz0ctscrsy7mp2ne7khfz8wu2uqsu4msfvxnlt6qfsmfrhr0",
            proof_server_url="http://localhost:6300",
        )
    except ProofServerConnectionError as e:
        print(f"ERROR: {e}")
        sys.exit(1)
    
    # Print connection status
    wallet_short = client.wallet_address[:40] + "..."
    print(f"Wallet        {wallet_short}")
    print(f"Proof Server  localhost:6300  OK connected")
    
    # b) Train model (skip if already exists)
    model_path = Path.home() / ".midnight" / "models" / "iris_rf.joblib"
    if not model_path.exists():
        print("Model         iris_rf.joblib  training...")
        client.ai.train_iris()
    else:
        print("Model         iris_rf.joblib  OK loaded")
    
    print("-" * 54)
    
    # c) Run ZK inference
    try:
        result = client.ai.predict_private(features=features)
    except Exception as e:
        print(f"\nERROR: {e}")
        sys.exit(1)
    
    # d) Print output
    print()
    print("[PRIVATE]  Input features:       [SEALED]  ZK sealed")
    print("[PRIVATE]  Raw probabilities:    [SEALED]  ZK sealed")
    print()
    print("-" * 54)
    print()
    print(f"[PUBLIC]   Prediction:           {result.prediction}")
    print(f"[PUBLIC]   Confidence:           {result.confidence * 100:.2f}%")
    print(f"[PUBLIC]   Model hash:           {result.model_hash[:16]}...")
    print()
    print("-" * 54)
    print()
    print(f"[PROOF]    Proof hash:           {result.proof_hash[:16]}...")
    print(f"[PROOF]    Proof bytes (hex):    {result.raw_proof_bytes[:32]}...")
    print(f"[STORED]   Receipt:              {result.receipt_path}")
    print()
    print("-" * 54)
    print()
    print("The private input NEVER left this machine.")
    print("The ZK proof was generated by the Midnight proof server.")
    print("Anyone can verify the prediction is correct - nobody can see the input.")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nInterrupted.")
        sys.exit(1)
    except Exception as e:
        print(f"\nFATAL ERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
